---
title: Elisa - Aseprite animation data classes
author: Christian Bitter
date: '2021-01-31'
slug: []
categories:
  - General
tags:
  - aseprite
  - Elisa
  - Game Programming
  - pygame
---

Unfortunately, the last couple of weeks weren't as Elisa-productive as I had anticipated. Partly, this was due to the typical work-buzz that surrounds the starting into a new year, i.e. everyone is full of anticipation and wants to carry the new year's resolution momentum into the workplace. Specifically, this meant a lot of communication and coordination leading to low to no eagerness to engage Elisa or Python or game programming for that matter outside of work. On the other hand because progress was somewhat slow for Elisa I rekindled my love for data analysis again. Actually, I bought [Gelman, Hill and Vehtaris' - Regression and Other Stories](https://avehtari.github.io/ROS-Examples/) in December of last year, simply for two reasons. Firstly, I absolutely enjoyed Gelman and Hill's other book and secondly I needed to do something for my other live - Data. While your mileage may vary, I believe the trio are excellent educators and together with the other great text of applied data analysis - [Statistical Rethinking- by Richard McElreath](https://xcelab.net/rm/statistical-rethinking/), Regression and Other Stories will likely take you on a grand tour that is equally insightful as it is curiosity-sparking outside of the craze du jour.

Clearly this article is not about data analysis, this might be something for the future. At this point in time, I just like to point out that in the latest update to Elisa you will find support for reading the [Aseprite JSON animation format](https://www.aseprite.org/docs/cli/). While I am far from a Pixel artist, I enjoy Aseprite quite a bit for the philosophy it brings to Pixel art creation. That is, it offers sophisticated tools in an environment that equally feels liberating and not overwhelming at the same time by simply reducing its interface to the pixel art style as well - no chrome gets in your way. Anyhow, as mentioned Elisa allows you to read a Aseprite created animation JSON, which together with some updates to Elisa's sprite-based animation focus will form the backbone to supporting 2D animation for our future work. In conjunction with Tiled for tile-based level editing, Elisa should then be primitive enough to allow us creating simple 2D games. Let's hope for some creativity injection in the future then :O.
