baseURL = "https://christianbitter.github.io/"
publishDir = "docs"
title = "Christian Bitter"
theme = "hugo-theme-m10c"
languageCode = "en-us"
defaultContentLanguage = "en-us"
paginate = 5
draft = false # if set to true, changes will not be published
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit", "\\.utf8", "\\.md$"]
enableEmoji = true
canonifyurls = true
relativeurls = true

disqusShortname = ""

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/post/"
    weight = -110
    
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = -100
    
  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = -90

[params]
  author = "Christian Bitter"
  description = "I am a Business Intelligence Leader and full-stack Data Scientist in the digital Agriculture space."
  menu_item_separator = " - "
  [[params.social]]
    name = "github"
    url = "https://github.com/christianbitter"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/christi26164848"

  # Brown theme
  #[params.style]
  #  darkestColor = "#463625"
  #  darkColor = "#2a3738"
  #  primaryColor = "#eeee6a"
  #  lightColor = "#96a879"
  #  lightestColor = "#ffffff"

  # Green theme
  #[params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  primaryColor = "#dad865"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"

  # Red and black theme
  #[params.style]
  #  darkestColor = "#d35050"
  #  darkColor = "#212121"
  #  primaryColor = "#ffffff"
  #  lightColor = "#a2a2a2"
  #  lightestColor = "#d3d3d3"
