---
title: A full-stack data scientist in the mlops-sphere
author: Christian Bitter
date: '2021-03-04'
slug: []
categories:
  - MLOps
tags:
  - machine-learning
  - machine-learning-operations
  - aws
  - mlops
  - ml
  - full-stack data science
---

Dear readership,

In the past, when it came to content for this blog, I have mostly ventured into Python-based game development with our Elisa series. Surely, this is an important part of my personal interests and hopefully it is of some value to you. At the same time I have to recognize that while ideas are plentiful the creation of content takes time and is typically balanced with the many areas that demand our attention family and business among the most prominent ones.

Furthermore, I recognize there might be other aspects of the computing space that more closely align with my day-to-day vocation as a full-stack Data Scientist and Business Intelligence leader in the digital agricultural space. Since moving data and insight on the AWS stack makes up a formidable portion of my wake-time, technical and personal development and frankly personal interest, you might wonder why not infuse these day-to-day topics with the elements of writing ...

So, from now on this blog will also venture into topics like data science, machine learning, machine learning operations and data engineering. I hope that this serves you - read you soon!
